### ISSUE TITLE
Substrate 2.0.0

### ISSUE THREAD

**Issue by LaurentTrk** [centrifuge/go-substrate-rpc-client#101]
Hi guys,

The Substrate v2.0.0 has been released. 
Would it be possible to update the go-substrate-rpc-client to work with this substrate release ?
I prepared a pull request for that purpose : https://github.com/centrifuge/go-substrate-rpc-client/pull/100

I hope it's ok for you :)
Thanks.

**Comment by mikiquantum** [comment]
Fixed by #100
