### ISSUE TITLE
Invalid Transaction

### ISSUE THREAD

**Issue by jackliu8722** [centrifuge/go-substrate-rpc-client#106]
hi, when run the makeASimpleTransfer, i got an error "makeASimpleTransfer", what's wrong with it.

**Comment by jackliu8722** [comment]
when i run a node with substrate-node-templete,  SimpleTransfer is ok, but i connect to rpc.polkadot.io for transfering dot, it got invalid transaction error, how can i fix it?

**Comment by mikiquantum** [comment]
@jackliu8722 I believe we need to update that example to include the TransactionVersion. Do you want to try it out using this example as reference? 
https://github.com/centrifuge/go-substrate-rpc-client/blob/c136426a4e020eb4948783916eb4a14f9f3e0343/teste2e/author_submit_extrinsic_test.go#L142
Make sure you set the correct transactionVersion, I believe is `5`.

**Comment by jackliu8722** [comment]
> @jackliu8722 I believe we need to update that example to include the TransactionVersion. Do you want to try it out using this example as reference?
> https://github.com/centrifuge/go-substrate-rpc-client/blob/c136426a4e020eb4948783916eb4a14f9f3e0343/teste2e/author_submit_extrinsic_test.go#L142
> 
> 
> Make sure you set the correct transactionVersion, I believe is `5`.

thank for your replay
i set the transactionVersion value from runtime, 
rv, err := api.RPC.State.GetRuntimeVersionLatest()
transactionVersion = rv.TransactionVersion
but i got the same error.

**Comment by mikiquantum** [comment]
@jackliu8722 have you seen this? https://github.com/centrifuge/go-substrate-rpc-client/issues/99#issuecomment-703846813

Can you check if that solves the problem? 

In addition does the account has enough balance?

Cheers,

**Comment by vedhavyas** [comment]
@jackliu8722 is this still an issue? Have you tried what @mikiquantum suggested?

**Comment by vedhavyas** [comment]
Closing this as there is no response from OP. Please open it again if you have more info for the team to reproduce the issue on latest release

**Comment by DmitriyMolch** [comment]
Got the same issue

**Comment by cdamian** [comment]
@DmitriyMolch which version of this library do you use and which chain are you running?
