### ISSUE TITLE
unable to find field Multisig_MultisigApproval for event #1 with EventID [31 1]

### ISSUE THREAD

**Issue by CryptoBadBoy** [centrifuge/go-substrate-rpc-client#110]
Hello
It error is falling when i decode event records on some blocks. Example, 4940400 block for kusama

	hash, err := api.RPC.Chain.GetBlockHash(number)
	if err != nil {
		return err
	}

	meta, err := api.RPC.State.GetMetadata(hash)
	if err != nil {
		return err
	}

	key, err := types.CreateStorageKey(meta, "System", "Events", nil, nil)
	if err != nil {
		return err
	}

	raw, err := api.RPC.State.GetStorageRaw(key, hash)
	if err != nil {
		return err
	}

	events := types.EventRecords{}
	err = types.EventRecordsRaw(*raw).DecodeEventRecords(meta, &events)
	if err != nil {
		return err   ///<<- unable to find field Multisig_MultisigApproval for event #1 with EventID [31 1]
	}

**Comment by mikiquantum** [comment]
@CryptoBadBoy Thanks for reporting this. Seems that we have wrongly defined the Event Name. Instead of `Multisig_MultisigApproval` we did `Multisig_Approval`. Will push a fix soon that bundles as well newer events since last substrate updates.

**Comment by CryptoBadBoy** [comment]
@mikiquantum, Thank you very much!

**Comment by mikiquantum** [comment]
fixed by #111 . Please reopen if otherwise.
