### ISSUE TITLE
Replace subkey with go-subkey port

### ISSUE THREAD

**Issue by MakMuftic** [centrifuge/go-substrate-rpc-client#112]
Have you considered moving to [go-subkey port](https://github.com/vedhavyas/go-subkey) so that installing subkey is not needed? I see this port is made by @vedhavyas

I have replaced it on [this fork](https://github.com/NodeFactoryIo/go-substrate-rpc-client) and everything seems to be working as intended.

**Comment by mikiquantum** [comment]
Thanks @MakMuftic, I would refer to @vedhavyas to check and confirm that the library is ready for prod use, before moving on with the PR open.

**Comment by vedhavyas** [comment]
@MakMuftic things that are missing in the port:
- Update deps to latest
- support for multiple schemes.

First one is straightforward.
Regarding the second, We have an open issue to support other schemes, and this is a simple change with the current subkey while requires some work to include the schemes on the subkey port.

While I lean towards using the subkey port, I would want to wait until we figure the feasibility of adding other schemes to the port. 

Note: we do not need a full functionality, just the ability to sign and verify for a given scheme, while the subkey binary has much more

**Comment by mpetrunic** [comment]
Are you using go-substrate-rpc-client in some end product? How do you distribute subkey binary?

Would it make more sense for this library to use subkey compiled to wasm?

**Comment by vedhavyas** [comment]
@mpetrunic With WASM, we need to write a wrapper on top of the subkey to compile to WASM.

**Comment by mpetrunic** [comment]
> @mpetrunic With WASM, we need to write a wrapper on top of the subkey to compile to WASM.

We would just need go wrapper over existing wasm binary generated from rust.
I looked into it, only mature wasm runtime in go doesn't support windows yet so not really a viable option. How hard is it to support multiple schemes in go-subkey? Is there some spec? We could help out.

**Comment by vedhavyas** [comment]
> We would just need go wrapper over existing wasm binary generated from rust.

ATM subkey is a cmd line with no exported functions for us to call on the Go side, so we would need to write a wrapper on subkey and export the required functions and then use it on the Go side.

> How hard is it to support multiple schemes in go-subkey? Is there some spec? We could help out.

When I wrote the port, I put everything in sr25519 including key derivation etc... ideally, those need to be moved out. Then remaining substrate schemes for signing and verifying needs to be included. We could use the libs that Gossamer uses. Unfortunately, there is no spec for this ATM. But happy to support you folk if you want to give it a shot 👍

**Comment by mpetrunic** [comment]
> ATM subkey is a cmd line with no exported functions for us to call on the Go side, so we would need to write a wrapper on subkey and export the required functions and then use it on the Go side.

Polkadot.js already made wrapper with exported required functions:
https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/rs/ed25519.rs

But I don't think it's worth doing that

> When I wrote the port, I put everything in sr25519 including key derivation etc... ideally, those need to be moved out. Then remaining substrate schemes for signing and verifying needs to be included. We could use the libs that Gossamer uses. Unfortunately, there is no spec for this ATM. But happy to support you folk if you want to give it a shot +1

Gonna talk to chainsafe to see what they are planning but would love to resolve this :slightly_smiling_face:

**Comment by vedhavyas** [comment]
@MakMuftic @mpetrunic I just made a v1 release with all the schemes here - https://github.com/vedhavyas/go-subkey/releases/tag/v1.0.0

**Comment by vedhavyas** [comment]
@MakMuftic @mpetrunic I have had a chance to add the remaining crypto schemes to this release - https://github.com/vedhavyas/go-subkey/releases/tag/v1.0.0

**Comment by mpetrunic** [comment]
> @MakMuftic @mpetrunic I have had a chance to add the remaining crypto schemes to this release - https://github.com/vedhavyas/go-subkey/releases/tag/v1.0.0

That's really nice of you 😄 Thank you.

Does that mean, if we update https://github.com/centrifuge/go-substrate-rpc-client/pull/114 it can be merged? 🙂

**Comment by vedhavyas** [comment]
@mikiquantum and I will get back on that soon.

**Comment by vedhavyas** [comment]
@MakMuftic @mpetrunic would you like to update the PR with latest port ?

**Comment by MakMuftic** [comment]
@vedhavyas I updated PR
