### ISSUE TITLE
Outdated examples at pkg.go.dev

### ISSUE THREAD

**Issue by ChinmayPatel** [centrifuge/go-substrate-rpc-client#117]
I just tried the examples (simpleTransfer example in particular) at https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client#pkg-examples and ran into a bunch of compatibility issue.

Eventually, I got it working using the main_test.go file and the answer at centrifuge/go-substrate-rpc-client#99 .

Can someone update the docs on the pkg.go.dev site? I'm new to go and not sure how to do it. If you can point me in the right direction, I can update the examples myself.

**Comment by vedhavyas** [comment]
@ChinmayPatel docs should be updated automatically. Can you try the latest master. That examples are updated there. Thy should work for SubstrateV3 based chain
