### ISSUE TITLE
How to get extrinsic data from the block?

### ISSUE THREAD

**Issue by ChinmayPatel** [centrifuge/go-substrate-rpc-client#118]
I'm trying to read details in the extrinsic call, but I'm not sure how to go about it.

So far, I have 
* received the blocked based on the hash string 
```
  var blockHashString = "0xd7a1c8e7fb89dcf72895a03d0a64b0aeb36e11aa7ab3e9bf036975b2d3b4a2c7";
  blockHash, err := types.NewHashFromHexString(blockHashString);
  if(err != nil) {
    panic(err)
  }

  // Get the block
  block, err := api.RPC.Chain.GetBlock(blockHash)
  if(err != nil){
    panic(err)
  }
```

* looping through extrinsics
```
  // Go through each Extrinsics
  for i, ext := range block.Block.Extrinsics {
    fmt.Println("EXT #  ", i)
    fmt.Println("EXT Details  ", ext)
  ...
  ...
  }
```

* located the `Args` as `Extrinsics.Method.Args`
```
  // inside the for loop described above
    fmt.Println("EXT Args Details  ", ext.Method.Args)
```

But the value of `Args` is an array of bytes (`[] byte`) (example below)
```
[220 188 40 21 96 60 227 172 245  ... 116 97 110 100 97 114 100 32 84 105 109 101 41]
```

I'm not sure how to get the full argument details out of this. Do I need to decode it further? It looks to be decoded already. 

What should be next step? Looking forward to a nudge in the right direction.

**Comment by mikiquantum** [comment]
@ChinmayPatel To be able to give a meaning to the arguments passed to the Call, first you would need to identify which pallet and function was called by resolving it from the callIndex `Extrinsics[n].Method.CallIndex` by finding it from the metadata at the block number when the extrinsic was included in the block.

Then you will need to decode the `Extrinsics[n].Method.Args` into the type of each argument in the function signature loaded from the metadata.

**Comment by ChinmayPatel** [comment]
Thanks for the quick response @mikiquantum . 

So, I need to build the reverse lookup function of `metadata.FindCallIndex('string')`. Is that correct? Is there an existing function like that in the library? If not, I'm happy to submit a PR to support that functionality.

**Comment by ChinmayPatel** [comment]
Also, we are trying to parse the `utility` pallet and the `batch` function. I can't seem to find a `utility` type inside the `types` function. Does that exist? Correct me if I'm wrong.

**Comment by ChinmayPatel** [comment]
Update; I can't seem to find the module based on the index. My `extrinsic.Method.CallIndex.SectionIndex` is 34 but there is not module with the same index. Below are some code snippest to explain my situation futher. 

First I'm reading a block and printing each extrinsic's `CallIndex`. 

```
  var blockHashString = "0xd7a1c8e7fb89dcf72895a03d0a64b0aeb36e11aa7ab3e9bf036975b2d3b4a2c7";
  blockHash, err := types.NewHashFromHexString(blockHashString);
  if(err != nil) {
    panic(err)
  }

  // Get the block
  block, err := api.RPC.Chain.GetBlock(blockHash)
  if(err != nil){
    panic(err)
  }

  // Go through each Extrinsics
  for i, ext := range block.Block.Extrinsics {
    fmt.Println("EXT #  ", i)
    fmt.Println("EXT CallIndex  ", ext.Method.CallIndex)
  ...
  ...
  }

```

One of the `ext` should be a `utility.batch`. It's CallIndex is `{34 122}', but none of the modules printed in the next code matches the `CallIndex.SectionIndex` of `34`. It's pretty weird!

Then, I'm grabbing the metadata when the block was generated and printing each module `name` and `index`. 
```
  var blockHashString = "0xd7a1c8e7fb89dcf72895a03d0a64b0aeb36e11aa7ab3e9bf036975b2d3b4a2c7";
  blockHash, err := types.NewHashFromHexString(blockHashString);
  if(err != nil) {
    panic(err)
  }

  meta, err := api.RPC.State.GetMetadata(blockHash)
  if err != nil {
    panic(err)
  }

  for i, mod := range meta.AsMetadataV12.Modules{
    fmt.Println("index: ", mod.Index, " \t for  module: ", mod.Name );
    i++
  }

```

Just to give more clarity about the call, it's a `utility.batch` call with two calls within it (`transfer` and `remark`).  

Either I'm not understanding the client library or how the utility batch extrinsic are represented as a module or both. 

How can I parse this extrinsic so that I can read the contents of the extrinsic?

**Comment by ChinmayPatel** [comment]
Update: It's still not working, but I have isolated the issue. 

I pulled the same block using the JS library. It was showing the correct CallIndex `{26 0}` instead of incorrect `{34 122}`. Who should be the right person to verify if the decoder is decoding correctly.

**Comment by ChinmayPatel** [comment]
This issue is not resolved, but the problem is different. Creating a new issue at https://github.com/centrifuge/go-substrate-rpc-client/issues/120 and closing the issue.

**Comment by ChinmayPatel** [comment]
```
@ChinmayPatel To be able to give a meaning to the arguments passed to the Call, first you would need to identify which pallet and function was called by resolving it from the callIndex Extrinsics[n].Method.CallIndex by finding it from the metadata at the block number when the extrinsic was included in the block.
```

Then you will need to decode the Extrinsics[n].Method.Args into the type of each argument in the function signature loaded from the metadata.

**Comment by vedhavyas** [comment]
@ChinmayPatel is this still an issue ?

**Comment by ChinmayPatel** [comment]
Unfortunately, not! We created a sample code @ https://github.com/blockxlabs/centrifuge-go-substrate-rpc-examples/blob/main/main.go. The aim is to read a batch transaction that has a transfer and a remark. We couldn't make it work using Centrifuge, so we made it work using another library as you can see at https://github.com/blockxlabs/centrifuge-go-substrate-rpc-examples/blob/main/main.go#L59. 

For the purpose of consistency, we would love to make it work using the Centrifuge library. You can see our attempt at https://github.com/blockxlabs/centrifuge-go-substrate-rpc-examples/blob/main/main.go#L296. 

Let me know the best way to solve this issue.

**Comment by ChinmayPatel** [comment]
This is resolved now. Thanks for the help @LaurentTrk (https://github.com/LaurentTrk) . 

Here is the code that might help others unbundle this. 

```
	// Go through each Extrinsics
	for i, ext := range block.Block.Extrinsics {
		if ext.Method.CallIndex.SectionIndex == 16 && ext.Method.CallIndex.MethodIndex == 0 {
			decoder := scale.NewDecoder(bytes.NewReader(ext.Method.Args))

			// determine number of calls
			n, err := decoder.DecodeUintCompact()
			if err != nil {
				return err
			}
			fmt.Println("CALLS # ", i, " --> ", n)
			for call := uint64(0); call < n.Uint64(); call++ {
				callIndex := types.CallIndex{}
				err = decoder.Decode(&callIndex)
				if err != nil {
					return err
				}
				fmt.Println("CALLINDEX # ", i, " --> ", callIndex)
				callFunction := findModule(metadata, callIndex)
				for _, callArg := range callFunction.Args {
					if callArg.Type == "<T::Lookup as StaticLookup>::Source" {
						var argValue = types.AccountID{}
						_ = decoder.Decode(&argValue)
						fmt.Println(callArg.Name, " = ", argValue)
					}
					if callArg.Type == "Compact<T::Balance>" {
						var argValue = types.UCompact{}
						_ = decoder.Decode(&argValue)
						fmt.Println(callArg.Name, " = ", argValue)
					}
					if callArg.Type == "Vec<u8>" {
						var argValue = callArg.Name
						_ = decoder.Decode(&argValue)
						fmt.Println(callArg.Name, " = ", argValue)
					}
				}
			}
		}
	}
	return nil

}


func findModule(metadata *types.Metadata, index types.CallIndex) types.FunctionMetadataV4 {
	for _, mod := range metadata.AsMetadataV12.Modules {
		if mod.Index == index.SectionIndex {
			fmt.Println("Find module  ", mod.Name)
			return mod.Calls[index.MethodIndex]
		}
	}
	panic("Unknown call")
}
```

Note for self (and others): If you see weird behaviour in the library, ensure that you are importing the right version.
