### ISSUE TITLE
Issue when fetching AccountInfo

### ISSUE THREAD

**Issue by MakMuftic** [centrifuge/go-substrate-rpc-client#119]
I used code from [Example (TransactionWithEvents)](https://godoc.org/github.com/centrifuge/go-substrate-rpc-client#ex-package--TransactionWithEvents), but I have a problem with fetching `AccountInfo`. It fails with this error:

```
type *types.AccountInfo does not support Decodeable interface and could not be decoded field by field, error: type *struct { Free types.U128; Reserved types.U128; MiscFrozen types.U128; FreeFrozen types.U128 } does not support Decodeable interface and could not be decoded field by field, error: Cannot read the required number of bytes 16, only 13 available
```

I am running `polkadot --dev` where `//Alice` is trying to make transaction

**Comment by vedhavyas** [comment]
@MakMuftic Looks like `AcocuntData` definition is different in your runtime. can you check what is the AccountStore you are using?
Is it balances or system module?
If you are using system pallet for storing account info, then please check the AccountData you are using? Ideally, this should be Balances::AcocuntData

**Comment by vedhavyas** [comment]
@MakMuftic is this still an issue?

**Comment by MakMuftic** [comment]
@vedhavyas Sorry, had a few crazy days so I forgot to respond here. Your clue helped me, so this is not an issue anymore. Tnx for the help.
