### ISSUE TITLE
cannot find module providing package

### ISSUE THREAD

**Issue by heipacker** [centrifuge/go-substrate-rpc-client#121]
build command-line-arguments: cannot load github.com/ethereum/go-ethereum/common: cannot find module providing package github.com/ethereum/go-ethereum/common

**Comment by vedhavyas** [comment]
@heipacker Could you give more info on the command you have used?

**Comment by vedhavyas** [comment]
Closing this due to no response from OP. PLease open this if you have more info for us to reproduce the issue with latest release
