### ISSUE TITLE
Missing MetatData.AsMetadataV12.Modules 

### ISSUE THREAD

**Issue by zadmarbella** [centrifuge/go-substrate-rpc-client#124]
Awesome library 👍👍👍👍

But we are seeing an issue when building on v2.0.0 with same variable defined on two places.
It looks to be resolved here https://github.com/centrifuge/go-substrate-rpc-client/pull/108
but when we try upgrade to v2.0.0-rc6.2 we are missing the Metadata.AsMetadataV12.Modules

Please advise.
Thanks

**Comment by mikiquantum** [comment]
Hi @zadmarbella, 
that release is on v2.0.0-RC6, just before substrate v2.0.0 was released, and that didn't contain metadata v12. If you need compatibility with v2 then you cannot use the substrate RC6 one, just use the released v2.0.0 or master for latest types.

**Comment by zadmarbella** [comment]
Hi, @mikiquantum 

We are compiling our project off a docker container FROM golang:1.15.5  image as part of a build pipeline. 

Thanks.

**Comment by mikiquantum** [comment]
I believe I need more info since I just tried building with this sample dockerfile successfully, from the GSRPC parent dir:

```
FROM golang:1.15.5

RUN mkdir -p $GOPATH/src/github.com/centrifuge/go-substrate-rpc-client
WORKDIR $GOPATH/src/github.com/centrifuge/go-substrate-rpc-client
COPY . .

RUN make install
```

**Comment by zadmarbella** [comment]
It looks like the ENV CGO_ENABLED=0 root cause.

We are able to reproduce it with this dockerfile

```
FROM golang:1.15.5

ENV GOBIN=/go/bin
ENV GOPATH=/go
ENV CGO_ENABLED=0
ENV GOOS=linux

RUN mkdir -p $GOPATH/src/github.com/centrifuge/go-substrate-rpc-client
WORKDIR $GOPATH/src/github.com/centrifuge/go-substrate-rpc-client

COPY . .

RUN go build
```
