### ISSUE TITLE
go-substrate-rpc-client execute the contract deployed in Ink?

### ISSUE THREAD

**Issue by qqliaoxin** [centrifuge/go-substrate-rpc-client#127]
Hello, I am a Go developer. I recently studied go-substrate-rpc-client and want to use it to implement the client of substrate. But I found no relevant implementation examples of author_submitAndWatchExtrinsic. Author_submit_and_watch_extrinsic_test.go on the gitHub repository is related to The data structure of polkadot{.js} is not the same. So I would like to ask you some examples of how you can update the gitHub Go version, or tell me how to implement it.

**Comment by vedhavyas** [comment]
you can find an example of making a simple balance transfer using author_SubmitAndWatch - https://github.com/centrifuge/go-substrate-rpc-client/blob/master/main_test.go#L397
