### ISSUE TITLE
AccountInfo  struct could need to modify because  gavin fix such code

### ISSUE THREAD

**Issue by zyjblockchain** [centrifuge/go-substrate-rpc-client#129]
![image](https://user-images.githubusercontent.com/40423181/105369626-b424c080-5c3d-11eb-8785-845fb84f2c69.png)

**Comment by vedhavyas** [comment]
@zyjblockchain the type change that was introduced would break back compatibility with the previous clients. Runtime types would change from version to version and, hence, we suggest you to overrides the types that are different from the default ones provided by the lib.
