### ISSUE TITLE
storage FreeBalance not found within module Balances

### ISSUE THREAD

**Issue by dungdang95** [centrifuge/go-substrate-rpc-client#130]
I use func check balance for example but it return error
```
alice, err := types.HexDecodeString("0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")
	if err != nil {
		fmt.Println("HexDecodeString")
		panic(err)
	}

	key, err := types.CreateStorageKey(meta, "Balances", "FreeBalance", alice, nil)
	if err != nil {
		fmt.Println("CreateStorageKey")
		panic(err)
	}
```

and err is 
` --- FAIL: TestNeoTestSuite/TestGetBalance (1.46s)
        suite.go:63: test panicked: storage FreeBalance not found within module Balances
            goroutine 8 [running]:
            runtime/debug.Stack(0xc000159748, 0x147ba60, 0xc00005b4f0)
            	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/debug/stack.go:24 +0x9d
            github.com/stretchr/testify/suite.failOnPanic(0xc000102200)
            	/Users/admin/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:63 +0x57
            panic(0x147ba60, 0xc00005b4f0)
            	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
            github.com/inc-backend/crypto-libs/dot.(*DotService).GetBalance(0xc000148300, 0x1515025, 0x22, 0x100e701, 0x8, 0xc000139380)
            	/Users/admin/Desktop/INC-BACKEND/crypto-libs/dot/dot.go:66 +0x4d9
            github.com/inc-backend/crypto-libs/dot.(*DotTestSuite).TestGetBalance(0xc00000e760)
            	/Users/admin/Desktop/INC-BACKEND/crypto-libs/dot/dot_test.go:63 +0x4b
            reflect.Value.call(0xc000127f20, 0xc000010b80, 0x13, 0x150804a, 0x4, 0xc000057ec0, 0x1, 0x1, 0xc000057ca0, 0x100beea, ...)
            	/usr/local/Cellar/go/1.13.5/libexec/src/reflect/value.go:460 +0x5f6
            reflect.Value.Call(0xc000127f20, 0xc000010b80, 0x13, 0xc000057ec0, 0x1, 0x1, 0xd78, 0x0, 0x1865288)
            	/usr/local/Cellar/go/1.13.5/libexec/src/reflect/value.go:321 +0xb4
            github.com/stretchr/testify/suite.Run.func1(0xc000102200)
            	/Users/admin/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:158 +0x390
            testing.tRunner(0xc000102200, 0xc0000b8090)
            	/usr/local/Cellar/go/1.13.5/libexec/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/usr/local/Cellar/go/1.13.5/libexec/src/testing/testing.go:960 +0x350`

**Comment by mikiquantum** [comment]
@dungdang95 I can't find the `FreeBalance` storage in the `Balances` pallet. Which version of substrate are you using?

**Comment by dungdang95** [comment]
V2.1.0

**Comment by mikiquantum** [comment]
@dungdang95 you just gave me the version of go-substrate-rpc-client I want to know the version of the Parity Substrate based chain you are connecting against.

**Comment by dungdang95** [comment]
I use westend testnet and rpc is wss://westend-rpc.polkadot.io. It is wrong? I dont know version of it.

**Comment by mikiquantum** [comment]
Just to step back for a moment, your goal is to get the free balance of an account. I have never used that storage key and I am not sure it is valid.
This is a simple snippet to get the balance of an account:

```
type AccountInfo struct {
	Nonce    types.U32
	Refcount types.U32
	Data     struct {
		Free       types.U128
		Reserved   types.U128
		MiscFrozen types.U128
		FreeFrozen types.U128
	}
}

func main() {
	api, err := gsrpc.NewSubstrateAPI("wss://westend-rpc.polkadot.io")
	if err != nil {
		panic(err)
	}
	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}
	alice, err := types.HexDecodeString("0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")
	if err != nil {
		fmt.Println("HexDecodeString")
		panic(err)
	}
	key, err := types.CreateStorageKey(meta, "System", "Account", alice, nil)
	if err != nil {
		panic(err)
	}
	var accountInfo AccountInfo
	ok, err := api.RPC.State.GetStorageLatest(key, &accountInfo)
	if err != nil || !ok {
		panic(err)
	}
	fmt.Println(accountInfo.Data.Free)
}
```

**Comment by dungdang95** [comment]
Can you check your Telegram inbox?
