### ISSUE TITLE
ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Multisig.0")

### ISSUE THREAD

**Issue by RJman-self** [centrifuge/go-substrate-rpc-client#134]
It seems polka update the Multisignature structure?

**Comment by RJman-self** [comment]
I encountered this error when I called Multisig.as_multi of polkadot (substrate)

**Comment by RJman-self** [comment]
////BEGIN: Create a call of MultiSignTransfer
	mulMethod := "Multisig.as_multi"

	var threshold = uint16(2)
	// parameters of multiSignature
	Alice, err := types.NewAddressFromHexAccountID("0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")
	Bob, err := types.NewAddressFromHexAccountID("0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48")

	var otherSignatories = []types.AccountID{Bob.AsAccountID, Alice.AsAccountID}
	var maybeTimepoint = types.TimePoint{
		Height: 11516,
		Index: 1,
	}

	//var maybeTimepoint = types.TimePoint{}
	//var maxWeight = types.NewWeight(220674000)
	var maxWeight = types.NewWeight(220674000)
	mc, err := types.NewCall(
		meta,
		mulMethod,
		threshold,
		otherSignatories,
		maybeTimepoint,
		c,
		false,
		maxWeight,
	)
	if err != nil {
		panic(nil)
	}

**Comment by vedhavyas** [comment]
@RJman-self could try this with latest master and let me know if you ar still sing this issue ?

**Comment by vedhavyas** [comment]
closing this due to no response from OP. Please open this again if you have more info for us to reproduce the issue with latest release
