### ISSUE TITLE
Basic Usage question

### ISSUE THREAD

**Issue by infinitedaremo** [centrifuge/go-substrate-rpc-client#136]
Were migrating our current functionality away from substrate sidecar API and was just wondering if its possible to replicate some of the features it has. 

Currently our requirement is simply to retrieve a block and its transaction and on that block simply iterate over the events for each transaction.

Whilst im able to query a block and the event records there are a few things im wondering how to do:

1. How do you get a transaction id similar to the format you see on [Polkascan](https://polkascan.io/polkadot/block/4013570#transactions)?
2. Is it possible to enumerate extrinsic transactions and filter the events that happened within that transaction? I've used types.EventRecordsRaw(*raw).DecodeEventRecords(m, &events) to get the events in the block but can't see a way to tie them to a specific transaction.
3. EventID's. I know its in the format of BlockID-EventIndex but im not sure if that index is available in the event record.
4. Is it possible to get the timestamp inherent?

I couldn't find any examples relating to these questions.

**Comment by vedhavyas** [comment]
@infinitedaremo there are some examples mentioned under `main_test.go` but not the complete feature set. 
We use GitHub issues for bugs and feature dev tracking. The discussions around there happen on our discord server under `substrate rpc` channel. I would suggest bringing these up there to find a potential solution for your use case.

Here is the discord invite: https://centrifuge.io/discord

**Comment by infinitedaremo** [comment]
Thanks ill ask on there
