### ISSUE TITLE
submit Extrinsic error

### ISSUE THREAD

**Issue by zyjblockchain** [centrifuge/go-substrate-rpc-client#142]
when I send a simple extrinsic, I get submit_extrinsic error `Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))` 
so, I run this lib uint test `./teste2e/author_submit_extrinic_test.go` func `TestChain_SubmitExtrinsic(t *Testing.T)` , and get the same error.

**Comment by vedhavyas** [comment]
@zyjblockchain is this from the latest v2.0.0 substrate ?

**Comment by vedhavyas** [comment]
@zyjblockchain any update on this?

**Comment by zyjblockchain** [comment]
> @zyjblockchain any update on this?

no，I find this lib do not support mutil address. so, send tx always get error.
now I use fork repo https://github.com/Snowfork/go-substrate-rpc-client to solve this problem。
if you have same problem, can try to use this fork repo

**Comment by vedhavyas** [comment]
@zyjblockchain the latest master on this branch will support multi address. Do try that and open the ticket if you still face the issue
