### ISSUE TITLE
get free balance decode response inaccurate

### ISSUE THREAD

**Issue by wuxuejie** [centrifuge/go-substrate-rpc-client#154]
I use func check balance for example but it response inaccurate
````
func (n *Dot) GetTestBalance() (float64, error) {
	addr := "143wEi2R1ArxtoKgHPEpNaB3sXCp5hwM4xKNxzc4DzCdAgyY"
	hexAddress := SS58ToHex(addr)
	fmt.Printf("\t\n[dot]SS58ToHex:%s=%v", addr, hexAddress)
	api, err := gsrpc.NewSubstrateAPI(n.Url)
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}
	btAddress, _ := types.HexDecodeString(hexAddress)
	key, err := types.CreateStorageKey(meta, "System", "Account", btAddress, nil)
	if err != nil {
		panic(err)
	}
	var accountInfo types.AccountInfo
	ok, err := api.RPC.State.GetStorageLatest(key, &accountInfo)
	if !ok {
		return float64(0), nil
	}
	if err != nil {
		panic(err)
	}
	blaFloat64, ok := decimal.NewFromBigInt(accountInfo.Data.Free.Int, -10).Float64()
	fmt.Printf("\t\n[dot]ss58Address=%v,bigint=%v,blaFloat64=%v", addr, accountInfo.Data.Free.Int, blaFloat64)
	return blaFloat64, nil
}
````
Print out：[dot]ss58Address=143wEi2R1ArxtoKgHPEpNaB3sXCp5hwM4xKNxzc4DzCdAgyY,bigint=44435731588581425152,blaFloat64=4.443573158858143e+09

The `143wEi2R1ArxtoKgHPEpNaB3sXCp5hwM4xKNxzc4DzCdAgyY` balance =1.0345 DOT，Why is the result 4443573158.8581425152
![yue](https://user-images.githubusercontent.com/31883495/117435406-6a4bb600-af60-11eb-9331-ef1468b8a342.png)

**Comment by SpaceTdlong** [comment]
I have the same problem. How to decode

**Comment by vedhavyas** [comment]
Please use 
```
type AccountInfo struct {
	Nonce       U32
	Consumers   U32
	Providers   U32
	Sufficients U32
	Data        struct {
		Free       U128
		Reserved   U128
		MiscFrozen U128
		FreeFrozen U128
	}
}
```
as instead of default since the polkadot version changed this type. We will update it once a new version is released

**Comment by shulhan-tokenomy** [comment]
@vedhavyas Sorry to interject the closed issue, but what does this means "once a new version is released"? New version of what?

**Comment by vedhavyas** [comment]
Once we move to substrate v3 and default account data is as mentioned above, we can make a PR to update default AccountInfo in gsrpc
