### ISSUE TITLE
Incorrect event type

### ISSUE THREAD

**Issue by xx-labs** [centrifuge/go-substrate-rpc-client#157]
The Council_Voted field should be using EventCollectiveVoted type instead of EventCollectiveProposed
https://github.com/centrifuge/go-substrate-rpc-client/blob/cf7d2b36c65143e711e36ef36c9bc1011e542601/types/event_record.go#L117

**Comment by vedhavyas** [comment]
@xx-labs thank you for reporting. Would you like to give a PR with that change ?
Else I'll get to it :)

**Comment by xx-labs** [comment]
Hi,

I submitted the PR https://github.com/centrifuge/go-substrate-rpc-client/pull/158
I don't seem to be able to link it to this issue?

Thanks!
