### ISSUE TITLE
Support metadata version 13

### ISSUE THREAD

**Issue by icodezjb** [centrifuge/go-substrate-rpc-client#159]

**Comment by rjman-ljm** [comment]
@-@

**Comment by ebarakos** [comment]
This issue is blocking us. Could you give us an estimate on when version 13 will be supported?

**Comment by zyjblockchain** [comment]
I have give up this repo, because update is too slow

**Comment by TUTUBIG** [comment]
me too

**Comment by TUTUBIG** [comment]
@zyjblockchain which repo do you use?

**Comment by ThreeAndTwo** [comment]
@TUTUBIG I think it's this. https://github.com/itering/subscan-essentials
