### ISSUE TITLE
Failed to get event metadata by using `GetStorage` with V13

### ISSUE THREAD

**Issue by raindust** [centrifuge/go-substrate-rpc-client#165]
When I try to upgrade [ChainBrdige](https://github.com/ChainSafe/ChainBridge) (which depends on RSRPC to interact with substrate) with V13 go the following error：
```
Events is a map, therefore requires precisely one argument. received: 2
```

The following is the code that got this error:
```
        meta := l.conn.getMetadata()
	key, err := types.CreateStorageKey(&meta, "System", "Events", nil, nil)
	if err != nil {
		return err
	}

	var records types.EventRecordsRaw
	storage, err := l.conn.api.RPC.State.GetStorage(key, &records, hash)
	if err != nil {
		return err
	}
```
And you can check the details at: https://github.com/tearust/ChainBridge/blob/main/chains/substrate/listener.go#L193

I think @ParthDesai my help me, thanks

**Comment by ParthDesai** [comment]
@raindust This is happening because the new `GetStorage` api takes variadic argument depending upon the key type (as received by Metadata). 

I will be opening a PR to `Chainbridge` repo shortly.

**Comment by raindust** [comment]
I have tested it and it works for me, thanks @ParthDesai
