### ISSUE TITLE
creating new substrate API returns "unsupported metadata version 13"

### ISSUE THREAD

**Issue by ultd** [centrifuge/go-substrate-rpc-client#176]
When running this: 

```go 
api, err := gsrpc.NewSubstrateAPI(fmt.Sprintf("https://polkadot--rpc.datahub.figment.io/apikey/%s/", figmentAPIKey))
if err != nil {
    log.Panic(err)
}
```

Getting this error: 

```
unsupported metadata version 13
```

It seems this version is supported [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/35e1b61fc8ac5d591a60fb7bbcc3fef3dc4f0a8c/types/metadata.go#L130) but still returning error.

**Comment by vedhavyas** [comment]
please use the latest release that supports v13. If the problem still exists, please reopen this ticket with version information and anything else you think wouldd help us reproduce the issue
