### ISSUE TITLE
question: How to get extrinsic events from block?

### ISSUE THREAD

**Issue by muhamadazmy** [centrifuge/go-substrate-rpc-client#178]
Sorry about this, i didn't know where to ask questions!
So, i call an extrinsic on substrate (custom pallet) and it raises an event. When i use this block hash to inspect the block on polkadot. The inspect view shows my successful extrinsic call AND the event itself 

![image](https://user-images.githubusercontent.com/10920323/126800797-f0b76c0a-5bf8-4841-8c1d-5f0ba6c8924a.png)

But in code, when I use the go client, I get the block via the same hash: I can only see the list of extrinsics, but no events. My question is how can I read the events from the that black (events with certain name as per screenshot) including it's data.

Thank you

**Comment by mikiquantum** [comment]
@muhamadazmy Events are part of the storage and not linked in the block itself. Instead you would need to query storage for the Events and filter by the blocknumber. Something like this:
```
key, err := types.CreateStorageKey(meta, "System", "Events", nil, nil)
...
i := YOURBLOCKNUMBER
bh, err := api.RPC.Chain.GetBlockHash(uint64(i))
...
raw, err := api.RPC.State.GetStorageRaw(key, bh)
...
events := types.EventRecords // Make sure this struct contains all the events that you care about
err = types.EventRecordsRaw(*raw).DecodeEventRecords(meta, &events)
...
if len(events.SmartContratModule_ContractCreated) > 0 { // Event found, get info from event params
...
}
```
Make sure that you create your own event structs, since this library only supports core substrate ones by default.

**Comment by muhamadazmy** [comment]
@mikiquantum thank you so much for your answer, I will give it a try. Sorry about the late response, I was on a holiday :)

**Comment by muhamadazmy** [comment]
@mikiquantum one more question. How to check also if an extrinsic fails ? since there is no event in that case

**Comment by DylanVerstraete** [comment]
@mikiquantum if there are multiple extrinsics in a block, how to filter on the ones that you (we) submitted? There is no field `who` on `System.extrinsic_failed` Event..

**Comment by netrikare** [comment]
> @mikiquantum 

You can get extrinsic index that event belongs to and use it to extract extrinsic signer from signature.
 
```
extrinsics := getExtrinsics(blockHash)
for _, event := range events.System_ExtrinsicFailed {
 extrinsicIndex := event.Phase.AsApplyExtrinsic
 who := extrinsics[extrinsicIndex].Signature.Signer.AsID
}
```

**Comment by DylanVerstraete** [comment]
@netrikare thank you so much! :)
