### ISSUE TITLE
Decode BlockNumber as uncompact uint rather than compact uint

### ISSUE THREAD

**Issue by tolak** [centrifuge/go-substrate-rpc-client#186]
I noticed GSRPC decodes BlockNumber as a compact uint by default, see [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/bbcac286d0817f85223a3defc13d00d5a1106387/types/header.go#L65), however, many events defined in substrate pallets  use uncompact uint BlockNumber. When people add their custom event types( including GSRPC own types), they would get events decoding failed.
So i suggest  decode BlockNumber as uncompact uint by default and introduce a new type, e.g. CompactBlockNumber, to act as a compact version

**Comment by vedhavyas** [comment]
@tolak the goal of the gsrpc is to let users bring in their own types that deviate from the substrate standard type. The block number is used in the header is encoded compact. If your types uses regaulr ints, you can create those types and use it out of the box. If you find any discrepancies with standard substrate type, please let us know here

**Comment by tolak** [comment]
@vedhavyas Yeah, the BlockNumber in header is encoded compact, however some events defined in substrate pallets use uncompact encoding instead. This would case event decoding failed in GSRPC, for example, event type  [EventSchedulerScheduled](https://github.com/centrifuge/go-substrate-rpc-client/blob/bbcac286d0817f85223a3defc13d00d5a1106387/types/events.go#L1089) defined in GSRPC used BlockNumber as type of ```When```, but in substrate side, When is defined as regular uint BlockNumber, see [here](https://github.com/paritytech/substrate/blob/f84ac630acccbfadc9f7cd8364fc43e03d743103/frame/scheduler/src/lib.rs#L198). It is easy to make a mistake if developer hasn't check whether the event argument(BlockNumber) is encode compact.

**Comment by vedhavyas** [comment]
Gotcha. Would you like to give a PR with you prosed changes @tolak ?

**Comment by cdamian** [comment]
Closing this for now, please let us know if you still need help.
