### ISSUE TITLE
Unknown error occurred when trying to query storage

### ISSUE THREAD

**Issue by DylanVerstraete** [centrifuge/go-substrate-rpc-client#189]
this code exits with panic: Unknown error occurred.

```
package main

import (
	"fmt"

	gsrpc "github.com/centrifuge/go-substrate-rpc-client/v3"

	"github.com/centrifuge/go-substrate-rpc-client/v3/types"
)

func main() {
	api, err := gsrpc.NewSubstrateAPI("ws://localhost:9944")
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}

	// Subscribe to system events via storage
	key, err := types.CreateStorageKey(meta, "System", "Events", nil, nil)
	if err != nil {
		panic(err)
	}

	lbh, err := api.RPC.Chain.GetBlockHash(1)
	if err != nil {
		panic(err)
	}

	ubh, err := api.RPC.Chain.GetBlockHash(2000)
	if err != nil {
		panic(err)
	}

	rawSet, err := api.RPC.State.QueryStorage([]types.StorageKey{key}, lbh, ubh)
	if err != nil {
		panic(err)
	}

	fmt.Println(rawSet)

}
```

What is going on?

**Comment by vedhavyas** [comment]
As discussed in the discord, you would need to have archival node to fetch old data. Hence the error from `QueryStorage`.

Closing this. Please open it if you still see the issue after connecting to archival node

**Comment by DylanVerstraete** [comment]
Problem persists even when connecting to an archival node

**Comment by DylanVerstraete** [comment]
In my opinion, throwing an error: `Unknown error occurred` is not very descriptive.. It looks like there is something wrong in the code rather than an issue implementing it.

**Comment by DylanVerstraete** [comment]
Update:

When running a 3 node setup when 2 nodes are validators and 1 node is archival. It seems to work when connecting to one of the 2 validator nodes, but it does not work when connecting to an archival node

**Comment by DylanVerstraete** [comment]
Update: I am receiving 2021-09-23 10:02:03  Unknown error: UnsafeRpcCalled(UnsafeRpcError) when trying to submit it to the archival node
