### ISSUE TITLE
Metadata v14 support

### ISSUE THREAD

**Issue by kaichen** [centrifuge/go-substrate-rpc-client#196]
After module v9110 block minted, now the NewSubstrateAPI function would throw `unsupported metadata version 14` error on both polkadot and kusama.

Wondering about v14 support.

**Comment by elricWu** [comment]
unsupported metadata version 14

**Comment by yaoyf888** [comment]
@kaichen Do you support metadata version 14?

**Comment by GooSatoru** [comment]
@mikiquantum what's the progress now, i can't use gsrpc connect any endpoint.

**Comment by GooSatoru** [comment]
@vgeddes @mikiquantum any update for this? the sdk does't update as a long time.

**Comment by vedhavyas** [comment]
Done through #206

**Comment by NunoAlexandre** [comment]
Thanks for all your patience and eagerness. We have just [released v.4.0.0](https://github.com/centrifuge/go-substrate-rpc-client/releases/tag/v4.0.0) with the Metadata v14 support included 🚀
