### ISSUE TITLE
Missing events on gsprc. 

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/go-substrate-rpc-client#203]
```
err="unable to find event with EventID [48 100] in metadata for event #4: module index 48 out of range"
```

With v3 substrate, we want to double check if the frame events are added to the events record

**Comment by NunoAlexandre** [comment]
@vedhavyas is this issue related to #52 by any means? They seem to be separate things, one being concerned with an event record failed to deserialise to a (missing) type def while this one seems to be related to a failed search but maybe there's some overlap I could learn about?

**Comment by vedhavyas** [comment]
@NunoAlexandre similar issue but with older version of substrate. We might be missing some more with latest substrate.
But this one https://github.com/centrifuge/go-substrate-rpc-client/issues/56 pretty much encompass the missing events during the initialisation
