### ISSUE TITLE
about Vec<u8> or Vec<Balance>, Which type should I use?

### ISSUE THREAD

**Issue by 99Kies** [centrifuge/go-substrate-rpc-client#210]
I didn't find what I wanted under `types`, I didn't know how to assign to this type.

**Comment by 99Kies** [comment]
use this?
```Go
type VecU8 = []types.U8
```

**Comment by 99Kies** [comment]
I want to ask you a question about `string`.
`ink_prelude::string::String`

**Comment by 99Kies** [comment]
[u8; 32]

**Comment by NunoAlexandre** [comment]
@99Kies I am missing context to your question. Could you provide me with that?

**Comment by NunoAlexandre** [comment]
@99Kies please re-open when you are able to provide more details on that issue.
