### ISSUE TITLE
Discussion: Combine Map, DoubleMap, and NMap 

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/go-substrate-rpc-client#215]
> so the type is not different for DoubleMap and NMap ?
> 
_Originally posted by @vedhavyas in https://github.com/centrifuge/go-substrate-rpc-client/pull/206#discussion_r750077136_

## The problem

In the comment thread linked above, @vedhavyas suggested that we should still handle the three types of Maps in v14: `Map`, `DoubleMap`, and `NMap`.

In v14, unlike <V14, the Storage Entry type only has two variants, `Plain`, and `Map` (See [the definition](https://github.com/polkadot-js/api/blob/80b581f0df87108c59f71e67d7c5fc5f8c89ec33/packages/types/src/interfaces/metadata/v14.ts#L86-L91))

The `Map` variant is now defined as:

``` ts
Map: {
        hashers: 'Vec<StorageHasherV14>',
        key: 'SiLookupTypeId',
        value: 'SiLookupTypeId'
      }
```

I and @vedhavyas discussed offline how the `key` value holds a `SiLookupTypeId`, which would therefore allow us to look up the actual type and therefore infer what (sub) type of `Map` we are dealing with.

To do so, we would need to change the function signatures of at least `IsDoubleMap` and `IsNMap()` to receive the `PortableRegistry`, so that in those functions we could look up the type associated with the map's key. However obvious, doing that would break the API for previous versions of the metadata. 

## Research

Changing the API of `IsDoubleMap` and `IsNMap` is not super trivial since they need to receive a value that allows for the implementation of those functions to look up a type based on some value, and this lookup mechanism should be version agnostic. I.e, it should be agnostic regarding the type of Registry, the index type it uses, and the type of the type associated with said index.

Given the nature of the problem, I looked for the commit where the change from having three Map variants to only having one happened. See [Combine Map/NMap/DoubleMap StorageEntryTypes](https://github.com/paritytech/frame-metadata/pull/23)

### Key Insights

As for motives to merge the three map variants into one, we have the following takeaways from the linked PR:

1. > As `NMap` is just a more generalized map, I don't see any reason to have 2 different storage entry types. We should be able to use `Map` for `NMap` and `Map`. 

2. > DoubleMap? It is just an NMap with 2 keys/hashers... Really is the same thing.

3. > /// One or more hashers, should be one hasher per key element.
    > hashers: Vec<StorageHasher>,
    > /// The type of the key, can be a tuple with elements for each of the hashers.
    > key: T::Type,

## Takeaways

So, now we have clarity over why and how the 3 map variants were combined into one.

We now know that what we called `DoubleMap` is now just a map with 2 keys and `NMap` is now just a map with `n` keys. Note, thus, how Nmap where key size == 2 is a DoubleMap.

We also now know that the length of `hashers` translates the number of keys of a Map, meaning that `Map` will have one hasher, "DoubleMap` will have two, and "NMap" will have n.

## Alternative Proposal

With all of this in mind, I propose that we don't go on breaking the API but instead:

- For v14, generalise the uses of `IsMap`, `IsDoubleMap`, and `IsNMap` to operate in a `NMap`-way: n keys, n hashers.

- Either have `IsNMap` and `IsDoubleMap` implementations for v14 returning a "not implemented" error or have them return based on the size of `hashers`, since that we know that the length of hashers must equal the number of keys. We should only do this if necessary since the value here really is in using the new abstracted and general `Map` type that can be either of the 3 old variants instead of perpetuating the notion of the 3 different variants.

**Comment by NunoAlexandre** [comment]
Reporting on an online discussion about this:

While at the metadata v14 there is only one, abstracted notion of Map, at the runtime level there are still 3. Therefore, there is value for users of this client to be able to tell them apart. Now, I am not sure if that is possible as I am quite sure that an NMap can have 1+ keys, making it impossible to tell an NMap of 1 key apart from a Map, and a map of 2 keys apart from a DoubleMap. I will have a look at that.

Thoughts are super welcome!

**Comment by NunoAlexandre** [comment]
Looking at `StorageNMap` in the substrate repo, I want to highlight the following bits:

``` rust
/// StorageNMap
/// A type that allow to store values for an arbitrary number of keys in the form of
/// `(Key<Hasher1, key1>, Key<Hasher2, key2>, ..., Key<HasherN, keyN>)`.
```

Examples in use:

- Nmap with two keys
``` rust
        #[pallet::storage]
	#[pallet::getter(fn nmap2)]
	pub type NMap2<T> = StorageNMap<
		Key = (NMapKey<Twox64Concat, u16>, NMapKey<Blake2_128Concat, u32>),
		Value = u64,
		MaxValues = ConstU32<11>,
	>;
```

- With three keys:

``` rust
        pub(super) type Account<T: Config<I>, I: 'static = ()> = StorageNMap<
		_,
		(
			NMapKey<Blake2_128Concat, T::AccountId>, // owner
			NMapKey<Blake2_128Concat, T::ClassId>,
			NMapKey<Blake2_128Concat, T::InstanceId>,
		),
		(),
		OptionQuery,
	>;
```


❗ The `NMap2` example above would be encoded as a Map with two hashers. With metadata v14, we would have no way to tell whether originally that type was a `StorageNMap` of 2 keys or a `DoubleMap`.

 If the idea with keeping the notion of the 3 different types of maps is to help users know what type in the runtime a type in the metadata had, we really can't provide them with that, it seems.

As things are looking, this would be a fair implementation of the three map check functions:

``` go
func (s StorageEntryMetadataV14) IsMap() bool {
	return s.Type.IsMap
}

func (s StorageEntryMetadataV14) IsNMap(registry RegistryMapV14) bool {
	return s.IsMap()
}

// A Storage Entry is a double map iff it is a map whose key is a tuple of two elements.
func (s StorageEntryMetadataV14) IsDoubleMap(registry RegistryMapV14) bool {
	return s.IsMap() && len(s.Hashers()) == 2
}
```

Then we can let the users decide whether they know/want to treat an NMap of 2 keys as an NMap/Map or as a DoubleMap. But then again, we just as well keep the new abstraction and let the users make that decision based on the length of the `Hashers()`, no?

**Comment by NunoAlexandre** [comment]
See https://github.com/paritytech/frame-metadata/pull/23#issuecomment-970612572 for what the authors of the merge of the 3 variants in the metadata have to say. Highlights:

- > There is no difference from a Map vs a NMap with one key, and a DoubleMap vs a NMap with 2 keys from the user perspective, the only difference is the slight difference in the function signatures in the rust implementation.

- > There is no difference from a storage-perspective in these, the number of keys just indicate how the entry is generated.

- > In metadata v14 there is no more Map/DoubleMap/NMap distinction. IMHO it would make sense to just follow where Substrate is headed and not make that distinction.


With that, following where substrate is headed seems to be the best indeed. We should stop supporting the notion of the 3 variants and instead provide `Map` as a map that has n keys. The user can always decide to do different things based on the number of keys, but we merge these concepts.

**Comment by mikiquantum** [comment]
Thanks @NunoAlexandre for  the research. Makes sense. 👍
