### ISSUE TITLE
Update gsrpc version in https://pkg.go.dev/

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/go-substrate-rpc-client#219]
I just realised that the latest published version of this library is dated Oct 6, 2020.

We should publish the latest version and (possibly) make all the gsrpc versions in between available too.

**Comment by NunoAlexandre** [comment]
@vedhavyas are you the man with the powers? :)

**Comment by vedhavyas** [comment]
@NunoAlexandre latest is automatically scrapped 
I can see the latest version here - https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre latest is automatically scrapped I can see the latest version here - https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4

hm. Why does it default to an older version tho 🤔 ? https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client defaults to `Version: v2.0.0+incompatible Latest Published: Oct 6, 2020`

**Comment by vedhavyas** [comment]
It is not defaulting to v2. Since the module version paths are important, you have to use v4 there
https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4

A simple search gives me v4 - https://pkg.go.dev/search?q=gsrpc&m=package

**Comment by NunoAlexandre** [comment]
My search flow was to search for `gsrpc go` on google and open the pkg.go.dev entry, which defaulted to that older version. For someone new to go I find that confusing. But I now see the little disclaimer on top `The highest tagged major version is v4.` 👍
