### ISSUE TITLE
use  api.RPC.Author.SubmitExtrinsic(ext)   to send extrinsic  failed

### ISSUE THREAD

**Issue by raojianli** [centrifuge/go-substrate-rpc-client#228]
`Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn't exist" }), desc: "Could not decode `Call::transfer::dest`" }), desc: "Could not decode `Call::Balances.0`" } })
`

**Comment by cdamian** [comment]
@raojianli Thank you for reaching out. We recently did an update where we added and adjusted types. Are you still able to reproduce this issue?

**Comment by cdamian** [comment]
Closing this for now, please let us know if you still need help.
