### ISSUE TITLE
SubmitExtrinsic always  return err

### ISSUE THREAD

**Issue by ParkerXie** [centrifuge/go-substrate-rpc-client#239]
Hi,when I run unittest to  SubmitExtrinsic ,it always return the follow err:
Message:"Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some(Error { cause: None, desc: \"unexpected first byte decoding Option\" }), desc: \"Could not decode `ChargeAssetTxPayment::asset_id`\" } })"

**Comment by puneetjindal3** [comment]
@ParkerXie Can you tell me what the exact error you are facing on blockchain? Reason I'm also facing the same error right now.
