### ISSUE TITLE
How to make NewCall Vector arguments work?

### ISSUE THREAD

**Issue by xtony77** [centrifuge/go-substrate-rpc-client#241]
If pallet method arguments is vactor data, What can I do?

pallet sample code
```Rust
pub struct Levels {
    pub level: u8
}
fn create_levels(origin, levels: Vec<Levels>) -> DispatchResult {...}
```

I tried this code, but it didn't work.
```Go
type Levels struct {
    Level types.U8
}
args := []Levels{
    {
        Level: types.NewU8(1),
    },
    {
        Level: types.NewU8(2),
    },
}
c, err := types.NewCall(meta, "Pallet.create_levels", args)
```

**Comment by mikiquantum** [comment]
Hi @xtony77 what is the error you are getting?

**Comment by xtony77** [comment]
I found the reason, is the pallet storage code written wrong, so no data can be found, the sample code no problem, close this issue. Thanks!
