### ISSUE TITLE
v4 types.AccountInfo struct analysis error?

### ISSUE THREAD

**Issue by l532857663** [centrifuge/go-substrate-rpc-client#256]
I failed to get the account information. I queried it and found that types.AccountInfo is missing a field, and there is 4byte of information in front of the Data field. please confirm  https://github.com/centrifuge/go-substrate-rpc-client/blob/v4.0.0/types/account_data.go

**Comment by aeryz** [comment]
It is probably `sufficients` field. See: https://docs.substrate.io/rustdocs/latest/frame_system/struct.AccountInfo.html. Also see https://github.com/polkadot-js/api/blob/85e7e3c11c668ecb7c0d7a0a346535c9cdb273b7/packages/types-augment/src/lookup/substrate.ts#L10.

**Comment by l532857663** [comment]
Yes, without this field, it is an error to get the account balance

**Comment by cdamian** [comment]
We'll do another update to the `AccountInfo` struct here - https://github.com/centrifuge/go-substrate-rpc-client/pull/366

Closing this for now.
