### ISSUE TITLE
query timestamp of one block

### ISSUE THREAD

**Issue by xianggy** [centrifuge/go-substrate-rpc-client#260]
Hi,
I can't find any RPC to get timestamp of one block.
Like the Nodejs API,  api.query.timestamp.now.at(blockHash).
How to get timestamp with this go-sdk?
Thansks.

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cdamian** [comment]
@xianggy Please let us know if you still need help with this. I will close this issue for now.
