### ISSUE TITLE
how to add custom type json ?

### ISSUE THREAD

**Issue by raojianli** [centrifuge/go-substrate-rpc-client#263]

**Comment by cdamian** [comment]
Hey @raojianli,

You can do that by creating a custom struct that implements the decodeable/encodeable interfaces, there are plenty examples on how to achieve that in the `types` folder, then use that struct to encode/decode to/from JSON.

**Comment by cdamian** [comment]
Also, we are looking into changing the current way of generating all these entities and we will keep the JSON aspect in mind when doing so. Thank you for contacting us!

**Comment by cdamian** [comment]
@raojianli please refer to - https://github.com/centrifuge/go-substrate-rpc-client/issues/251#issuecomment-1840630293
