### ISSUE TITLE
wasm trap: wasm `unreachable` instruction executed when calling SubmitExtrinsic 

### ISSUE THREAD

**Issue by freddyli7** [centrifuge/go-substrate-rpc-client#276]
Hey there! I was trying to integrate with GSRPC lib in my go project, and I got this error when calling `SubmitExtrinsic`:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/13714909/177372364-3c995324-c568-4fa7-acee-e7fe94f23846.png">

I was running two local relay chain nodes via docker container, version `0.9.24-22836e55d41`
GSRPC version `v4.0.2`, and I was following the example code in the doc [here](https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4#example-package-MakeASimpleTransfer) with a different sender(not Alice as hardcoded one in the example), this is how I got my sender:

```Golang
sender, err := signature.KeyringPairFromSecret("my mnemonic", 42)
```

Full logic is here:
```Golang
package main

import (
	"fmt"
	gsrpc "github.com/centrifuge/go-substrate-rpc-client/v4"
	"github.com/centrifuge/go-substrate-rpc-client/v4/signature"
	"github.com/centrifuge/go-substrate-rpc-client/v4/types"
	"math/big"
)

func TransferAsset(rpcEndpoint string, sender signature.KeyringPair, method string) {
	api, err := gsrpc.NewSubstrateAPI(rpcEndpoint)
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", meta.Version)
	health, err := api.RPC.System.Health()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", health)

	name, err := api.RPC.System.Name()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", name)

	chain, err := api.RPC.System.Chain()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", chain)

	version, err := api.RPC.System.Version()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", version)

	test2Account, err := types.NewAddressFromHexAccountID("0x4617579c92b915a76ade267fb42ba5a28f10b51686f84aa968b0270ea2fc7243") // TEST2 account
	if err != nil {
		panic(err)
	}

	c, err := types.NewCall(meta, method, test2Account, types.NewUCompactFromUInt(1000000000000))
	if err != nil {
		panic(err)
	}

	ext := types.NewExtrinsic(c)

	genesisHash, err := api.RPC.Chain.GetBlockHash(0)
	if err != nil {
		panic(err)
	}

	rv, err := api.RPC.State.GetRuntimeVersionLatest()
	if err != nil {
		panic(err)
	}

	key, err := types.CreateStorageKey(meta, "System", "Account", sender.PublicKey, nil)
	if err != nil {
		panic(err)
	}

	var accountInfo types.AccountInfo
	ok, err = api.RPC.State.GetStorageLatest(key, &accountInfo)
	if err != nil || !ok {
		panic(err)
	}

	options := types.SignatureOptions{
		BlockHash:          genesisHash,
		Era:                types.ExtrinsicEra{IsMortalEra: false},
		GenesisHash:        genesisHash,
		Nonce:              types.NewUCompactFromUInt(uint64(accountInfo.Nonce)),
		SpecVersion:        rv.SpecVersion,
		Tip:                types.NewUCompactFromUInt(0),
		TransactionVersion: rv.TransactionVersion,
	}

	err = ext.Sign(sender, options)
	if err != nil {
		panic(err)
	}

	hash, err := api.RPC.Author.SubmitExtrinsic(ext)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Transfer sent with hash %#x\n", hash)
}

package main

import "github.com/centrifuge/go-substrate-rpc-client/v4/signature"

func main() {
	sender, err := signature.KeyringPairFromSecret("my mnemonic", 42)
	if err != nil {
		panic(err)
	}
	TransferAsset("ws://localhost:9966", sender, "Balances.transfer")
}

```

**Comment by freddyli7** [comment]
Some more info:

I setup a local network with `v0.9.23` of polkadot binary and `v0.9.23` of polkadot-parachain binary, then tried the @polkadot/api with balance transfer, asset create, mint, transferKeepAlive etc. All works fine against my local network, but GSRPC doesn't. Same error as I mentioned above.

So I did a bit debugging, and I found that for the same balance.transfer transaction, the encoded tx on @polkadot/api and the GSRPC repo are a little bit different:

js ->   `0400004617579c92b915a76ade267fb42ba5a28f10b51686f84aa968b0270ea2fc7243070010a5d4e8`
go -> `0400ff4617579c92b915a76ade267fb42ba5a28f10b51686f84aa968b0270ea2fc7243070010a5d4e8`

As you can see there is a slight difference, so I tried to replace with the encoded tx from js into GSRPC, tx went through.

btw, I've tried `v4.0.2` and `v4.0.3`, neither works. the @polkadot/api version I tried is `8.11.3`

**Comment by freddyli7** [comment]
Found more info:

`NewCall()` in `github.com/centrifuge/go-substrate-rpc-client/v4/types` is trying to encode the types.Address but turned out `types.Address` didn't implement `scale.Encodeable` interface so that it tries to do type assertion and then call `Encode` method, however, the result starting with `255` instead of `0` for `types.Address`, and which eventually cause the wasm error. If I manually replace `225` to `0`, tx went through.

![image](https://user-images.githubusercontent.com/13714909/178595326-e6053c43-777b-4f33-8c0e-1ec1e63a8027.png)

**Comment by mikiquantum** [comment]
Hi @freddyli7 try changing the line
```
test2Account, err := types.NewAddressFromHexAccountID("0x4617579c92b915a76ade267fb42ba5a28f10b51686f84aa968b0270ea2fc7243") // TEST2 account
```
by
```
test2Account, err := types.NewMultiAddressFromHexAccountID("0x4617579c92b915a76ade267fb42ba5a28f10b51686f84aa968b0270ea2fc7243") // TEST2 account
```

**Comment by freddyli7** [comment]
hmm... ok it's finally working. The example is using `types.NewAddressFromHexAccountID`, maybe you guys should update that.  thanks @mikiquantum
