### ISSUE TITLE
what is the centrifuge endpoint ?

### ISSUE THREAD

**Issue by LXHLeaner** [centrifuge/go-substrate-rpc-client#282]
why the  endpoint "wss://fullnode.centrifuge.io" response the date is https://centrifuge-standalone-history.subscan.io/
but not the https://centrifuge.subscan.io/

**Comment by cdamian** [comment]
Hi @LXHLeaner I'm not sure I understood your question. If you are asking about the difference in data between the 2 subscan links that you mentioned, https://centrifuge-standalone-history.subscan.io/ points to the legacy/standalone chain from which we migrated a couple of months ago. https://centrifuge.subscan.io/ points to the latest running version.
