### ISSUE TITLE
Incorrect dependency?

### ISSUE THREAD

**Issue by vcastellm** [centrifuge/go-substrate-rpc-client#302]
According to `go.mod` it depends on https://github.com/centrifuge/go-substrate-rpc-client/blob/master/go.mod#L15 in the v4 but it's not working for me.

It only works for me if I manually add dependency on github.com/vedhavyas/go-subkey/v2

**Comment by timwu20** [comment]
This is failing for me as well when trying to import this package.
```
go: downloading github.com/vedhavyas/go-subkey v1.0.4
../go/pkg/mod/github.com/centrifuge/go-substrate-rpc-client/v4@v4.1.0/signature/signature.go:25:2: reading github.com/vedhavyas/go-subkey/go.mod at revision v1.0.4: unknown revision v1.0.4
../go/pkg/mod/github.com/centrifuge/go-substrate-rpc-client/v4@v4.1.0/signature/signature.go:26:2: reading github.com/vedhavyas/go-subkey/go.mod at revision v1.0.4: unknown revision v1.0.4
```
If you look at https://github.com/vedhavyas/go-subkey there is no version v1.0.4?

**Comment by cdamian** [comment]
Fix in - https://github.com/centrifuge/go-substrate-rpc-client/pull/366
