### ISSUE TITLE
extract utility batch extrinsic transaction from block

### ISSUE THREAD

**Issue by bhaagiKenpachi** [centrifuge/go-substrate-rpc-client#303]
I'm having trouble in extracting extrinsic details. I want to signer, signature, hash, utility batch <{ system::remark, balance::transfer }> details, fee e.t.c

Extrinsic tx:
https://westend.subscan.io/extrinsic/0xa9a708657612ce331f0ced07f648d46d810d1eb920aece0ba462226c56f2d1eb

package main

import (
	"fmt"
	dotc "github.com/centrifuge/go-substrate-rpc-client/client"
	dotRpc "github.com/centrifuge/go-substrate-rpc-client/rpc/chain"
	//dotRpc "github.com/centrifuge/go-substrate-rpc-client/rpc"
)

func main() {
	client, err := dotc.Connect("wss://westend-rpc.polkadot.io")

	if err != nil {
		fmt.Errorf("error in connecting %w", err)
	}

	rpcClient := dotRpc.NewChain(client)

	if err != nil {
		fmt.Errorf("error in rpc connection %w", err)
	}

	blockHash, err := rpcClient.GetBlockHash(12782886)

	if err != nil {
		fmt.Errorf("error in rpc connection %w", err)
	}

	blockInfo, err := rpcClient.GetBlock(blockHash)

	for _, extrinsic := range blockInfo.Block.Extrinsics {
		// to be filled. 
	}

}

**Comment by cdamian** [comment]
We don't have a way to directly address your use case, please see the below example of how we extract the timestamp from the `timestamp.set` extrinsic - https://github.com/centrifuge/go-centrifuge/blob/e9937c87e0e87fa19e365a58b77f2f375bef3e8c/identity/v2/service.go#L378

You could do something similar in your case.
