### ISSUE TITLE
 unsupported metadata version 14

### ISSUE THREAD

**Issue by pramoths** [centrifuge/go-substrate-rpc-client#312]
Getting unsupported metadata version 14, while creating new RPC client with the local latest substate node.

Current version not supported for the metadata version 14. 

Below is the minimal code to reproduce the issue

`package main

import (
	"fmt"

	gsrpc "github.com/centrifuge/go-substrate-rpc-client"
)

func main() {
	api, err := gsrpc.NewSubstrateAPI("ws://127.0.0.1:9944")
	if err != nil {
		
		fmt.Println("Error on New API : ",err)
	}
	hash, err := api.RPC.Chain.GetBlockHashLatest()
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(hash)
}`

**Comment by mikiquantum** [comment]
@pramoths can you try importing as:
```
github.com/centrifuge/go-substrate-rpc-client/v4 v4.0.0
```

**Comment by pramoths** [comment]
@mikiquantum thanks its working
