### ISSUE TITLE
AccountInfo struct should include Suffinents field to get correct account balance

### ISSUE THREAD

**Issue by 5QgKxT2j** [centrifuge/go-substrate-rpc-client#313]
Currently, we cannot get correct account balance because types.AccountInfo is missing Sufficients field.
I work around by writing the following code and confirm can get the correct balance.

```
	type ModifiedAccountInfo struct {
		Nonce       types.U32
		Consumers   types.U32
		Providers   types.U32
		Sufficients types.U32
		Data        struct {
			Free       types.U128
			Reserved   types.U128
			MiscFrozen types.U128
			FreeFrozen types.U128
		}
	}

	var accountInfo ModifiedAccountInfo
	ok, err := sc.SubstrateAPIClient.RPC.State.GetStorageLatest(key, &accountInfo)
```

The full answer is here.
https://substrate.stackexchange.com/questions/6292/how-to-get-human-readable-astr-balance-in-golang

**Comment by cdamian** [comment]
@5QgKxT2j fixed in - https://github.com/centrifuge/go-substrate-rpc-client/releases/tag/v4.0.10
