### ISSUE TITLE
test examples: throwing error (unsupported metadata version 14)

### ISSUE THREAD

**Issue by muddlebee** [centrifuge/go-substrate-rpc-client#346]
Getting the below error for [examples ](https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client) when connecting to polkadot or kusama RPC endpoints

> 2023/05/20 17:31:25 Connecting to wss://rpc.polkadot.io...
> panic: unsupported metadata version 14

**Comment by muddlebee** [comment]
I tested with westend RPC and Kusama RPC

**Comment by cdamian** [comment]
Please try the examples from - https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4, and let us know if you still need help.
