### ISSUE TITLE
Calls and subscriptions should accept a context

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/go-substrate-rpc-client#38]
Calls should accept a context so they can be cancelled and can receive a timeout. 

Subscriptions need a bit more investigation – a context could be used to cancel or timeout the subscription, but the current subscription logic already exposes an Unsubscribe method that can be used for both purposes.

**Comment by johnuopini** [comment]
I definitely need this, i create a client every 2/3 minutes to get data from chain, if the client gets stuck i have no way to cancel that call and retry, i haven't found any fix so far, having an additional constructor that accepts a context or add a context to the call would be great

**Comment by cdamian** [comment]
The `Client` interface will be updated here - https://github.com/centrifuge/go-substrate-rpc-client/pull/366 to include the `CallContext` method. We will not update any RPC clients as of now.
