### ISSUE TITLE
Not work when polkadot upgrade to 1.2.5

### ISSUE THREAD

**Issue by hugeroot001** [centrifuge/go-substrate-rpc-client#390]
return errors when send tx
panic: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x7098e - <unknown>!rust_begin_unwind
    1: 0xc97d - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
    2: 0x6f5327 - <unknown>!TaggedTransactionQueue_validate_transaction [recovered]
	panic: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed

**Comment by cdamian** [comment]
Hi @liuguangmao, can you please try out - https://github.com/centrifuge/go-substrate-rpc-client/pull/389 and let me know if that works for you?

**Comment by liuguangmao** [comment]
I‘v tried it before, it was not working either.

```
	newDynamicExtrinsic := extrinsic.NewDynamicExtrinsic(&c)
	err = newDynamicExtrinsic.Sign(kr, meta, extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{}),
		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(nonce))),
		extrinsic.WithTransactionVersion(rv.TransactionVersion),
		extrinsic.WithSpecVersion(rv.SpecVersion),
		extrinsic.WithGenesisHash(genesisHash),
		extrinsic.WithEra(types.ExtrinsicEra{IsMortalEra: false}, genesisHash),
	)

	if err != nil {
		panic(err)
		return
	}
	dynamicExtrinsic, err := api.RPC.Author.SubmitDynamicExtrinsic(newDynamicExtrinsic)
```

> Hi @liuguangmao, can you please try out - #389 and let me know if that works for you?

**Comment by cdamian** [comment]
Can you provide more info that we can use to debug this - how did you execute this extrinsic, what extrinsic is this, which chain are you using?
