### ISSUE TITLE
Transaction has a bad signature

### ISSUE THREAD

**Issue by ElleryHao** [centrifuge/go-substrate-rpc-client#397]
arguments:

`
    "amount":1000000,
    "from":"12BfJpQ9MW4a1QMNRPiyMyVm6QMZppT7U8syYss2NCp9Q7dD",
    "to":"13R2cmzYCvG1NWhHxvo7651Co1JSiyXU9uLD1dAzdidktgHm",
    "nonce":1,
    "tip":0,
    "blockHeight":21984302,
    "blockHash":"0xadd7b39654668d0697060ab6a95cd47d3753ccec8f006b5d60c840a67f63ec0f",
"specVersion" ：1002007
	"genesisHash"  : "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
	"txVersion"    = "4"
	"method" : "0500"
`

i use like this, and got signed raw tx : 
0x39028400345da418e84e6cd68d1a882780fcc675547f90c558da5149f9c4bb72666a8bff005fe937cd17308d7625cfaf53372a1f550eb7c076bcd05c9ff2326f38c6863319a4d2e3956bfcb8bec14946517ca4ac30f6efb025be8c425cf7761290e218bf0e000028000500006acbcca055473964d47ccd15b55661d0cf34efb81994c52195476ee7d7527b2b02093d00

but when i call author_submitExtrinsic, i can only get "Transaction has a bad signature"

**Comment by ElleryHao** [comment]
i use ed2519 to sign the transaction, i found examples using sr2519 instead

**Comment by cdamian** [comment]
@ElleryHao Hey, can you try this with the branch found here - https://github.com/centrifuge/go-substrate-rpc-client/pull/389, and lemme know if that works for you?

**Comment by ElleryHao** [comment]
> @ElleryHao Hey, can you try this with the branch found here - #389, and lemme know if that works for you?

i will try

**Comment by ElleryHao** [comment]
@cdamian hello, i use this branch and found it is ok for me
but how i can do this in mainnet?

**Comment by ElleryHao** [comment]
finally i succeeded to finish the submission task with adding 0x00

**Comment by ElleryHao** [comment]
i think i fix this by adding new bytes into serialized payload struct
