### ISSUE TITLE
unsupported metadata version 9

### ISSUE THREAD

**Issue by hellowaldoli** [centrifuge/go-substrate-rpc-client#43]
unsupported metadata version 9

How can support metadata version 9?

**Comment by philipstanislaus** [comment]
Support will be added next week

**Comment by hellowaldoli** [comment]
I tried again and found the same error

**Comment by philipstanislaus** [comment]
We did not yet get to the upgrade. Would appreciate a PR if this is blocking you. Thanks!

**Comment by boxhock** [comment]
@philipstanislaus How big of a PR are we talking to add support for metadata version 9? If noone were to create a PR, how long would you estimate it would take for you guys to get to this?

This is blocking us as well.

**Comment by philipstanislaus** [comment]
@boxhock it's probably a few types only, but I'd need to look into it. We are just upgrading our chain and will need metadata v9 in the next few days – I will implement them next.

**Comment by boxhock** [comment]
Awesome, thank you 👍

**Comment by hellowaldoli** [comment]
This is blocking me and I hope to solve this problem, thank you

**Comment by philipstanislaus** [comment]
@boxhock @hellowaldoli just came back from holidays and created a PR. Feel free to use that branch, I expect this to be reviewed and merged in the next days.
