### ISSUE TITLE
RUN Example_transactionWithEvents func ERROR

### ISSUE THREAD

**Issue by mym-xjl** [centrifuge/go-substrate-rpc-client#49]
Run "Example_transactionWithEvents" func in main_test.go, here "meta, err := api.RPC.State.GetMetadataLatest()" ret error is "type *types.StorageMetadata does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV5 does not support Decodeable interface and could not be decoded field by field, error: type *types.DoubleMapTypeV5 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 5 [recovered]
	panic: type *types.StorageMetadata does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV5 does not support Decodeable interface and could not be decoded field by field, error: type *types.DoubleMapTypeV5 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 5
"

**Comment by mym-xjl** [comment]
The node I am connecting to is: “Kusama CC-3”

**Comment by philipstanislaus** [comment]
Thanks for reporting this @mym-xjl . The issue comes most likely from the fact that there was a recent change in the hasher enum: https://github.com/paritytech/substrate/commit/bbb363f4320b4a72e059c0fca96af42296d5a6bf#diff-dd0e6529af8fd40ed337ed026cae22b8R276

Which version of [polkadot](https://github.com/paritytech/polkadot) are you running?

**Comment by mym-xjl** [comment]
> Thanks for reporting this @mym-xjl . The issue comes most likely from the fact that there was a recent change in the hasher enum: [paritytech/substrate@bbb363f#diff-dd0e6529af8fd40ed337ed026cae22b8R276](https://github.com/paritytech/substrate/commit/bbb363f4320b4a72e059c0fca96af42296d5a6bf#diff-dd0e6529af8fd40ed337ed026cae22b8R276)
> 
> Which version of [polkadot](https://github.com/paritytech/polkadot) are you running?

polkadot --version
polkadot 0.7.9-f23ce3e9-x86_64-linux-gnu

**Comment by philipstanislaus** [comment]
@mym-xjl thanks for your reply. 

Unfortunately we will most likely not get to solve this before mid of February, since our team is fully focussed on the launch of our next Testnet. 

Would appreciate a PR though – happy to provide guidance and review in a timely manner. Many thanks!

**Comment by philipstanislaus** [comment]
@mym-xjl I just updated GSRPC to support metadata v10 in #51, which includes the ability to decode the changed hasher enum.

This should solve your issue. Please comment here if this is still unsolved. Thanks!

**Comment by mym-xjl** [comment]
Thank you for your support. Happy Spring Festival~
