### ISSUE TITLE
Query historical system events on archive node

### ISSUE THREAD

**Issue by silentlight** [centrifuge/go-substrate-rpc-client#61]
Hello,

I was wondering what would be the easies method to query historical system events from archive node. I understand that I can subscribe to get system events, but I was wondering, since I run archive node how could I get system events at specific heigh. Any help would be much appreciated.

**Comment by philipstanislaus** [comment]
@silentlight just use `api.RPC.State.GetStorageLatest`, like this: 

```Go
api, err := gsrpc.NewSubstrateAPI(config.Default().RPCURL)
if err != nil {
	return err
}

meta, err := api.RPC.State.GetMetadataLatest()
if err != nil {
	return err
}

key, err := types.CreateStorageKey(meta, "Session", "Validators", nil, nil)
if err != nil {
	return err
}

blockHash, err := api.RPC.Chain.GetBlockHash(123)
if err != nil {
	return err
}

var validators []types.AccountID
err = api.RPC.State.GetStorage(key, &validators, blockHash)
if err != nil {
	return err
}

fmt.Printf("Current validators:\n")
for i, v := range validators {
	fmt.Printf("\tValidator %v: %#x\n", i, v)
}
```

**Comment by silentlight** [comment]
When I updated to last commit to include metadatav11 I am getting this error:
` *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field`, `received unexpected storage hasher type 6`. Any idea what I am doing wrong?

**Comment by philipstanislaus** [comment]
@silentlight thanks for the bug report. Please open a new issue for that. Thanks!
