### ISSUE TITLE
Decode Blocking Forever

### ISSUE THREAD

**Issue by ansermino** [centrifuge/go-substrate-rpc-client#63]
I have the following defined in my pallet:
```rust
pub struct ProposalVotes<AccountId, Hash> {
    votes_for: Vec<AccountId>,
    votes_against: Vec<AccountId>,
    hash: Hash,
}
```

And a corresponding Go declaration:
```go
type VoteState struct {
    VotesFor []types.AccountID
    VotesAgainst []types.AccountID
    Hash types.Hash
}
```

Calling `Decode` (inside `DecodeFromBytes()`) seems to never return. This only seems to be the case when the struct is non-empty.

Reproducible:
```go
// From RPC state query 
enc := hexutil.MustDecode("0x16078eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a4810000000")

var dec voteState
fmt.Println("Starting to decode")
err := types.DecodeFromBytes(enc, &dec)
fmt.Println("Finished decoding")
if err != nil {
	panic(err)
}

// Expected: VoteStatus {
//   VotesFor: []types.AccountID{types.NewAccountId(signature.TestKeyringPairAlice.PublicKey)},
//   VotesAgainst: []types.AccountID{},
//   Hash: prop.hash,
// } 
```

**Comment by philipstanislaus** [comment]
Something seems to be wrong with the encoding – how exactly do you query the RPC state? 

This test passes: 

```
func TestDecodeBlocking(t *testing.T) {
	type VoteState struct {
		VotesFor     []AccountID
		VotesAgainst []AccountID
		Hash         Hash
	}

	expected := VoteState{
		VotesFor:     []AccountID{NewAccountID(signature.TestKeyringPairAlice.PublicKey)},
		VotesAgainst: nil,
		Hash:         NewHash([]byte{0x1b}),
	}

	bz, err := EncodeToBytes(expected)
	assert.NoError(t, err)

	// enc := hexutil.MustDecode("0x16078eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a4810000000")

	var dec VoteState
	fmt.Println("Starting to decode")
	err = DecodeFromBytes(bz, &dec)
	fmt.Println("Finished decoding")
	assert.NoError(t, err)

	assert.Equal(t, expected, dec)
}
```

**Comment by philipstanislaus** [comment]
The encoded string is definitely wrong, right now the decoder tries to decode `736330181` items for `VotesFor`.

**Comment by philipstanislaus** [comment]
Changed decoding to error instead of trying to continue when no more bytes can be decoded: https://github.com/centrifuge/go-substrate-rpc-client/pull/64

**Comment by ansermino** [comment]
> Something seems to be wrong with the encoding – how exactly do you query the RPC state?

The input was generated by using the storage key created by GSRPC to query via RPC in the substrate UI.  

![Screenshot_2020-03-17_08-04-56](https://user-images.githubusercontent.com/14164624/76854733-07f89900-6826-11ea-81ca-4aca8ebab2e2.png)

**Comment by philipstanislaus** [comment]
Can you send me a link to the substrate code declaring that storage item? Thanks!

**Comment by ansermino** [comment]
https://github.com/ChainSafe/chainbridge-substrate/blob/c68f00d3608bade7fef61455b2d8ec5147ecfb36/src/lib.rs#L30-L36

**Comment by philipstanislaus** [comment]
One more thing – please send me a link or snippet how you got the storage key. Thanks!

**Comment by ansermino** [comment]
I was constructing the wrong key :man_facepalming: 

Thanks for fixing the error handling!

**Comment by philipstanislaus** [comment]
@ansermino no worries, at least there is no more hanging in GSRPC in the future in such cases :) 

Also looking at the substrate code, the storage query should return an `Option<ProposalVotes>`, so you need to have a custom decoding logic to account for the `Option`.
