### ISSUE TITLE
Incompatibility with Other Chain Configs

### ISSUE THREAD

**Issue by ansermino** [centrifuge/go-substrate-rpc-client#65]
Extrinsics are failing when submitted to the [`substrate-node-template` chain](https://github.com/substrate-developer-hub/substrate-node-template).

```
Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"))
```

GSRPC code can be found here: https://gist.github.com/ansermino/07df0dd8e35c522ec23c1d922860c786

This seems to have something to do with the type configuration for the chain (see https://polkadot.js.org/api/start/types.extend.html#impact-on-extrinsics)

**Comment by philipstanislaus** [comment]
@ansermino closing this as fixed by #68
