### ISSUE TITLE
Call contract through RPC

### ISSUE THREAD

**Issue by robdefeo** [centrifuge/go-substrate-rpc-client#67]
It is not possible to call a contract through the RPC client however it is supported in the [toolbox](https://polkadot.js.org/apps/#/toolbox).
 
![image](https://user-images.githubusercontent.com/1633235/77231434-c6078400-6b92-11ea-8f6d-f024520a5df8.png)

It is part of the contracts endpoint.

**Comment by philipstanislaus** [comment]
You are right, that has not been implemented yet. Would much appreciate if you would add a PR for it!

**Comment by ThreeAndTwo** [comment]
@philipstanislaus So is it still not supported now?

**Comment by philipstanislaus** [comment]
@ThreeAndTwo unfortunately not. @vedhavyas is maintaining this repository now - could you share some insights on the timeline @vedhavyas ?

**Comment by vedhavyas** [comment]
@ThreeAndTwo we are working on a timeline and priorities soon. Will keep you posted here.

**Comment by NunoAlexandre** [comment]
@vedhavyas could you post an update on this issue?

**Comment by cdamian** [comment]
Closing this for now as it no longer seems relevant.
