### ISSUE TITLE
Chain.GetBlock not work in 6f0547f2818d5fbc659d4a9be363bb4e02ab223d , but 461cf42e77c6d3b65fefa801a1aeddf04f1174cf

### ISSUE THREAD

**Issue by Peacess** [centrifuge/go-substrate-rpc-client#72]
Chain.GetBlock return error:   type *types.ExtrinsicSignatureV4 does not support Decodeable interface and could not be decoded fiel
final error is : errors.New("Not supported: l>4 encountered when decoding a compact-encoded uint")

**Comment by philipstanislaus** [comment]
@Peacess please provide more detail, e. g. which chain are you connected to?

**Comment by lucasvo** [comment]
@Peacess do you still have this issue?

**Comment by mikiquantum** [comment]
Closing for now, please reopen if you still have this issue using the latest release https://github.com/centrifuge/go-substrate-rpc-client/releases/tag/v2.0.0-rc6
