### ISSUE TITLE
Problem with metadatav11

### ISSUE THREAD

**Issue by silentlight** [centrifuge/go-substrate-rpc-client#73]
When I updated to last commit to include metadatav11 I am getting this error:
`*types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field, received unexpected storage hasher type 6.`

**Comment by silentlight** [comment]
Any workaround for this issue?

**Comment by silentlight** [comment]
@philipstanislaus Any idea on how to make it work?

**Comment by alanchchen** [comment]
> @philipstanislaus Any idea on how to make it work?

Hi @silentlight , I've made a patch myself. Not sure if it works for you.

https://github.com/consenlabs/go-substrate-rpc-client/commits/develop

**Comment by lucasvo** [comment]
@alanchchen do you think this could be turned into a pull request?

**Comment by mikiquantum** [comment]
New release https://github.com/centrifuge/go-substrate-rpc-client/releases/tag/v2.0.0-rc6 should fix this problem, otherwise please reopen.
