### ISSUE TITLE
How to extend EventRecords to match my custom substrate node

### ISSUE THREAD

**Issue by phpmaple** [centrifuge/go-substrate-rpc-client#74]
I have some custom events and types

**Comment by vedhavyas** [comment]
Here is an example of how you can extend types.Events with your custom events on substrate - https://github.com/centrifuge/go-centrifuge/blob/develop/centchain/extrinsic_status_task.go#L214

**Comment by phpmaple** [comment]
> Here is an example of how you can extend types.Events with your custom events on substrate - [centrifuge/go-centrifuge:centchain/extrinsic_status_task.go@`develop`#L214](https://github.com/centrifuge/go-centrifuge/blob/develop/centchain/extrinsic_status_task.go#L214) [](/centrifuge/go-centrifuge/blob/HEAD@{2020-04-14T11:03:34Z}/centchain/extrinsic_status_task.go#L214)

Thanks! and How I create custom types in my node, these could be in metadata, and  
match to this client!

**Comment by vedhavyas** [comment]
Not sure I understand your question :)

**Comment by phpmaple** [comment]
> Not sure I understand your question :)
If I have a type Trade struct In substrate node and it can be return when I query strorage or include in eventRecord payload
