### ISSUE TITLE
storage AccountNonce not found within module System

### ISSUE THREAD

**Issue by nikosk686** [centrifuge/go-substrate-rpc-client#78]
On `Example_makeASimpleTransfer` and wherever is applicable, 
this `types.CreateStorageKey(meta, "System", "AccountNonce", signature.TestKeyringPairAlice.PublicKey, nil)`
shoud become
`types.CreateStorageKey(meta, "System", "Account", signature.TestKeyringPairAlice.PublicKey, nil)`

**Comment by mikiquantum** [comment]
Thanks @nikosk686 for reporting it, would you create a PR to adapt it?

**Comment by nikosk686** [comment]
Hi @mikiquantum, I ve created a PR that changes all "AccountNonce" references with "Account".
Hope it is ok :)
