### ISSUE TITLE
Public key (hex):   0x

### ISSUE THREAD

**Issue by phpmaple** [centrifuge/go-substrate-rpc-client#80]
https://github.com/centrifuge/go-substrate-rpc-client/blob/6f0547f2818d5fbc659d4a9be363bb4e02ab223d/signature/signature.go#L41

after colon should be one or more space not exact one space

**Comment by lucasvo** [comment]
@phpmaple thanks for reporting this. Would you like to submit a fix for this?

**Comment by ansermino** [comment]
#83 might help with this
