### ISSUE TITLE
NewSubstrateAPI error

### ISSUE THREAD

**Issue by kunzhangs312** [centrifuge/go-substrate-rpc-client#81]
error message:
type *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.MapTypeV10 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 6 [recovered]
	panic: type *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.MapTypeV10 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 6

url: ws://47.108.199.133:9944

**Comment by tdmm** [comment]
I have the same error.

**Comment by mikiquantum** [comment]
@kunzhangs312 & @tdmm Thanks for reporting this. I believe since Identity hasher was included here: https://github.com/paritytech/substrate/commit/dd97b1478b31a4715df7e88a5ebc6664425fb6c6#diff-3c162d5f4ec03ec67b7cb5a6ba1eb665
We didnt update the type mapping. We will review internally and create a PR soon.
Thanks!

**Comment by zenghao1986** [comment]
> error message:
> type *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.MapTypeV10 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 6 [recovered]
> panic: type *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.StorageFunctionMetadataV10 does not support Decodeable interface and could not be decoded field by field, error: type *types.MapTypeV10 does not support Decodeable interface and could not be decoded field by field, error: received unexpected storage hasher type 6
> 
> url: ws://47.108.199.133:9944

I have the same error too!

**Comment by tdmm** [comment]
> @kunzhangs312 & @tdmm Thanks for reporting this. I believe since Identity hasher was included here: [paritytech/substrate@dd97b14#diff-3c162d5f4ec03ec67b7cb5a6ba1eb665](https://github.com/paritytech/substrate/commit/dd97b1478b31a4715df7e88a5ebc6664425fb6c6#diff-3c162d5f4ec03ec67b7cb5a6ba1eb665)
> We didnt update the type mapping. We will review internally and create a PR soon.
> Thanks!

I am looking forward to this pr!

**Comment by robdefeo** [comment]
I am having this error too, any update on the PR for this?

Looks like this is a duplication of https://github.com/centrifuge/go-substrate-rpc-client/issues/82

**Comment by mikiquantum** [comment]
We are upgrading our chain as well in the next 4 weeks, and we will need to fix this at the same time. In the meantime any contributions are more than welcome.

**Comment by mikiquantum** [comment]
Created this PR #89 to attempt to fix the above issues. If you could have a look and test out in your respective chains would be great.
