### ISSUE TITLE
types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field 

### ISSUE THREAD

**Issue by zenghao1986** [centrifuge/go-substrate-rpc-client#82]
when i code this:	
api, err := gsrpc.NewSubstrateAPI(mynoderul)
	if err != nil {
		panic(err)
	}
but occured this bug:
type *types.StorageMetadataV10 does not support Decodeable interface and could not be decoded field  .
How to fix this error?

**Comment by robdefeo** [comment]
Any progress on this?

**Comment by robdefeo** [comment]
A new testnet beresheet is released v38 and this failed on that network. Currently mainnet is at v31 these same changes will be applied soon. 
```
api, err := gsrpc.NewSubstrateAPI("ws://beresheet1.edgewa.re")
if err != nil {
panic(err)
}
```

I can not see any documentation for how decoding works in `go-substrate-rpc-client` can you provide an update on if you will fix this? This update will break the `go-substrate-rpc-client` soon.

**Comment by mikiquantum** [comment]
@robdefeo latest release https://github.com/centrifuge/go-substrate-rpc-client/releases/tag/v2.0.0-rc6 should solve this problem. Feel free to reopen if problem persists
