### ISSUE TITLE
events decode error 

### ISSUE THREAD

**Issue by Laighno** [centrifuge/go-substrate-rpc-client#91]
I get a storage raw `0x0c0000000000000080e36a09000000000200000001000000000000000000000000000200000002000000000000ca9a3b00000000020000` with key `System` `Events`. And this 55 bytes hex could not be decode with error `unable to decode field 2 event #1 with EventID [1 0], field Indices_IndexAssigned: unexpected EOF`.

**Comment by Laighno** [comment]
I found the problem: `type DispatchInfo struct {
	// Weight of this transaction
	Weight U32
	// Class of this transaction
	Class DispatchClass
	// PaysFee indicates whether this transaction pays fees
	PaysFee bool
}` . the weight should be U64 not U32.

**Comment by philipstanislaus** [comment]
Nice, thanks for reporting this. Could you create a PR for it? Many thanks!

**Comment by Laighno** [comment]
ok, I will create a PR later. another question, how can I get a transaction hash? I did't find any function about this.

**Comment by philipstanislaus** [comment]
@Laighno sorry for the late reply. The first return value of `hash, err := api.RPC.Author.SubmitExtrinsic(ext)` is the extrinsic hash. Hope that helps!
