### ISSUE TITLE
 unsupported metadata version 11

### ISSUE THREAD

**Issue by anzhaozhong** [centrifuge/go-substrate-rpc-client#93]

**Comment by lucasvo** [comment]
This is related to #73 and we're in the process of upgrading to RC6. We'll submit a PR soon.

**Comment by lucasvo** [comment]
Also check out #90 it brings you up to rc4.

**Comment by anzhaozhong** [comment]
How long does it take to support v11?

**Comment by anzhaozhong** [comment]
> Also check out #90 it brings you up to rc4.

How long does it take to support v11?

**Comment by lucasvo** [comment]
@mikiquantum is working on it. Perhaps you can give an update?

**Comment by xavierp1992** [comment]
Hi are there any updates on this? I am having this issue as well.

**Comment by mikiquantum** [comment]
@anzhaozhong  @xavierp1992 new release supports substrate chains up to v2.0.0-rc6 (included), with latest metadata 11 updates.
Let us know if this release fixes the problem
