### ISSUE TITLE
Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature when submitting to Polkadot with v2.0.0-rc6-0

### ISSUE THREAD

**Issue by RaghavSood** [centrifuge/go-substrate-rpc-client#99]
I'm using the example code from the godoc [here](https://godoc.org/github.com/centrifuge/go-substrate-rpc-client#example-package--MakeASimpleTransfer), but am unable to actually submit the signed transaction.

It fails with 

    Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature

which should already be solved according to #65 and #68.

Do we need to update anything from the example code for it to work?

**Comment by mikiquantum** [comment]
@RaghavSood Thanks for reporting, I believe we might have missed to update that example. I will do so.
In the meantime, can you try adding `TransactionVersion: 1,` to this block:
```
o := types.SignatureOptions{
		BlockHash:   genesisHash,
		Era:         types.ExtrinsicEra{IsMortalEra: false},
		GenesisHash: genesisHash,
		Nonce:       types.NewUCompactFromUInt(uint64(nonce)),
		SpecVersion: rv.SpecVersion,
		Tip:         types.NewUCompactFromUInt(0),
		TransactionVersion: 1,
	}
```
Let us know if that works

**Comment by RaghavSood** [comment]
@mikiquantum Thanks for the quick response.

Unfortunately, it fails with the same error.

**Comment by mikiquantum** [comment]
@RaghavSood We were only able to push the lib until v2.0.0-rc6. I believe Polkadot is in that version, if there is other type missing or incompatible we will have to debug it, to find out which one is causing this.
We will get back to you here as soon as possible.

**Comment by RaghavSood** [comment]
Just for reference, I performed an identical transaction with the typescript singer-cli.

Transaction:

From: 15M2jgjNBvwxuZyDNAWcyFheYPzvZ478m8UvFfKoLP1MeiSb
To: 15zd9gx4iiB2FzhTWeNnaE88MsYxCYdcQUMPWkXXv793Vd84
balances.transfer
Nonce 0
18800000000 plancks

The one produced by GSRPC serialized to:

 
 
 
 0x390284c037af84f31c86970d09e7dc1d001c4faaacd98dbd9fb5d15563fb43cf6c087801ee4894f2951d3151c72118bc45b9000ae62a2cd8b27e57bfa72ac72f26b9f0564e4cffd01bc0964fa0dbd842e13132912a4e7e84892b633c8a8f2a2004c6f3870000000500ffdce39ceac330ee75f1b45771aceda3a7f51eebd40586ea2fc90788f4449b441607003c916004

and failed with the error in the title.

The one produced by signer-cli serialized to

    0x390284c037af84f31c86970d09e7dc1d001c4faaacd98dbd9fb5d15563fb43cf6c087801c4f754cd01865694d1310f5df3d188629f2d023f3741ed8ff8735eb62ea91e33eb63162a960e55e419c3d884cab96d833de98968452d8c4dc902f3e237ba4f8c850100000500dce39ceac330ee75f1b45771aceda3a7f51eebd40586ea2fc90788f4449b441607003c916004

and was mined successfully

**Comment by RaghavSood** [comment]
Breaking it down a little further, I got:

```
Failing tx:
0x390284
c037af84f31c86970d09e7dc1d001c4faaacd98dbd9fb5d15563fb43cf6c0878
01
ee4894f2951d3151c72118bc45b9000ae62a2cd8b27e57bfa72ac72f26b9f0564e4cffd01bc0964fa0dbd842e13132912a4e7e84892b633c8a8f2a2004c6f387
0000000500ff
dce39ceac330ee75f1b45771aceda3a7f51eebd40586ea2fc90788f4449b4416
07
003c916004

Working tx:
0x390284
c037af84f31c86970d09e7dc1d001c4faaacd98dbd9fb5d15563fb43cf6c0878
01
c4f754cd01865694d1310f5df3d188629f2d023f3741ed8ff8735eb62ea91e33eb63162a960e55e419c3d884cab96d833de98968452d8c4dc902f3e237ba4f8c
850100000500
dce39ceac330ee75f1b45771aceda3a7f51eebd40586ea2fc90788f4449b4416
07
003c916004
```

Looks like the only difference is `0000000500ff` in the failing one in place of `850100000500` in the working one

**Comment by mikiquantum** [comment]
@RaghavSood Looking at it, will give an update here as soon as I find the problem.

**Comment by mikiquantum** [comment]
@RaghavSood I was able to send successfully send a balance transfer against `westend testnet` by setting:
```
TransactionVersion: 3,
```
As per: https://github.com/paritytech/polkadot/blob/d327000afb34a49c3b0ce7c80147cbea6434d429/runtime/westend/src/lib.rs#L93

For Polkadot seems that it should be `5` per https://github.com/paritytech/polkadot/blob/e9a004b9fc06f260a8bc98a0c28697457b28834f/runtime/polkadot/src/lib.rs#L99

If you get this error after trying this out:
```
panic: Verification Error: Execution: Trap: Trap { kind: Unreachable } [recovered]
panic: Verification Error: Execution: Trap: Trap { kind: Unreachable }
```
Let me know, bc I had to tweak something in the Address encoder to get it to work against `westend`. I am trying to get to the bottom of it.

**Comment by mikiquantum** [comment]
Tip: You can get the TransactionVersion programatically:
```
rv, err := api.RPC.State.GetRuntimeVersionLatest()
	if err != nil {
		panic(err)
	}
	fmt.Println(rv.TransactionVersion)
```

**Comment by mikiquantum** [comment]
If you face the error above, as a quick fix for now, specify these:
```
api, err := gsrpc.NewSubstrateAPI("wss://westend-rpc.polkadot.io")
if err != nil {
	panic(err)
}

opts := types.SerDeOptions{NoPalletIndices: true}
types.SetSerDeOptions(opts)
```
Just after the `api` has been instantiated.

The reason is that GSRPC was assuming that if the Indices pallet was included, then it was used as Lookup in the frame system and for validating transactions. Which is true for the node spec in substrate repo:
https://github.com/paritytech/substrate/blob/fb82769a21b1328c95b9dacdf24b626eff35b692/bin/node/runtime/src/lib.rs#L169
https://github.com/paritytech/substrate/blob/fb82769a21b1328c95b9dacdf24b626eff35b692/bin/node/runtime/src/lib.rs#L753

BUT not for Kusama/westend/polkadot:
https://github.com/paritytech/polkadot/blob/e9a004b9fc06f260a8bc98a0c28697457b28834f/runtime/kusama/src/lib.rs#L136
https://github.com/paritytech/polkadot/blob/e9a004b9fc06f260a8bc98a0c28697457b28834f/runtime/kusama/src/lib.rs#L642

Not really sure the reasoning behind these, but will add some comments around it in GSRPC.

**Comment by crossle** [comment]
I face the same problem, `{"jsonrpc":"2.0","error":{"code":1002,"message":"Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature","data":"RuntimeApi(\"Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\")"},"id":1603358274813614000}`
I use the transaction version 5

**Comment by crossle** [comment]
BTW, this library support ed25519 signature? i try use `	sig := ed25519.Sign(key, enc)` but failed :"Invalid Transaction","data":"Transaction has a bad signature"

**Comment by mikiquantum** [comment]
@crossle thanks for pointing it out. Even though `subkey` obviously supports ed25519 signatures we haven't exposed the `scheme` option to the sign/verify functions, and therefore always defaulting to `Sr25519`. 
Will add an issue to expose that option.

Regarding the above error, Can you provide the code snippet? Are you connecting to Polkadot as well?

**Comment by frankli-dev** [comment]
This is the same issue with this one https://github.com/centrifuge/go-substrate-rpc-client/issues/133
The fix for v3 substrate is merged to master branch.

**Comment by vedhavyas** [comment]
yes. The latest master should fix the issues with v3 substrate chains. Closing this now. Please do open this if you are still facing the issues with chains running with MultiAddress and Multisignature
